config/routes.rb
Pplugin::Application.routes.draw do

  resource :session, :only => [:new, :create, :destroy]

  match 'login' => 'openids#pixnet', :as => :login

  match 'logout' => 'openids#logout', :as => :logout

  match '/info' => 'account#info', :as => :info

  root :to => "home#index"

  resource :openid do
    get "pixnet", :on => :member
  end 

  resources :oauth_consumers do
    get "callback", :on => :member
  end

  resource :akismet

  resources :pshbs do # PubSubHubbub
    get "akismet", :on => :member
    post "akismet", :on => :member
  end

end

app/models/akismet.rb
class Akismet < ActiveRecord::Base
  belongs_to :user

  ENABLED_TYPE = [["啟用", true], ["關閉", false]]

  before_save :enabled_check
  after_create :subscribe

  protected
  def enabled_check
    if enabled_changed?
      enabled? ? subscribe : unsubscribe
    end
  end

  def subscribe
    pshb = GooglePshb.new("http://#{HOST_NAME}", "https://pubsubhubbub.appspot.com")
    pshb.subscribe("/pshbs/#{user.login}/akismet", "#{user.blog}/comments", user.generate_token)
  end

  def unsubscribe
    pshb = GooglePshb.new("http://#{HOST_NAME}", "https://pubsubhubbub.appspot.com")
    pshb.unsubscribe("/pshbs/#{user.login}/akismet", "#{user.blog}/comments", user.generate_token)
  end

  def validate
    Rakismet.key = apikey
    Rakismet.url = user.blog
    Rakismet.validate_key
  end
end

app/controllers/akismets_controller.rb
class AkismetsController < ApplicationController
  before_filter :login_required, :set_header

  def show
    @akismet = @current_user.akismet
    @pixnet = @current_user.pixnet
    redirect_to new_akismet_path if @pixnet.present? && !@akismet.present?
  end

  def new
    redirect_to akismet_path if current_user.akismet
    @akismet = Akismet.new(:user => current_user)
  end

  def create
    redirect_to akismet_path if current_user.akismet
    @akismet = Akismet.new(params[:akismet])
    @akismet.user = current_user
    if @akismet.save
      flash[:notice] = "新增成功"
      redirect_to akismet_path
    else
      flash[:error] = error_messages_from(@akismet)
      render :action => :new
    end
  end

  def edit
    @akismet = current_user.akismet
  end

  def update
    @akismet = current_user.akismet
    if @akismet.update_attributes(params[:akismet])
      flash[:notice] = "修改成功"
      redirect_to akismet_path
    else
      flash[:error] = error_messages_from(@akismet)
      render :action => :edit
    end
  end

  def destroy
    @akismet = current_user.akismet
    @akismet.destroy
    flash[:notice] = "刪除成功"
    redirect_to akismet_path
  end

  protected
  def set_header
    @header = "Akismet"
  end

end

app/views/akismets/_form.html.erb
<div data-role="fieldcontain">
  <%= f.label :apikey, Akismet.human_attribute_name(:apikey) %>
  <%= f.text_field :apikey %><br>
</div>

<div data-role="fieldcontain">
  <%= f.label :enabled, Akismet.human_attribute_name(:enabled) %>
  <%= f.select :enabled, Akismet::ENABLED_TYPE, {}, {"data-role" => "slider"} %>
</div>
<%= submit_tag "Submit" %>

app/views/akismets/edit.html.erb
<%= form_for @akismet, :url => akismet_path(@akismet), :html => { :class => :form } do |f| -%>
  <h2 class="title">修改 Akismet Key</h2>
  <%= render :partial => "form", :locals => {:f => f} %>
<% end -%>

app/views/akismets/new.html.erb
<div class="block">
  <div class="content">
    <h2 class="title">新增 Akismet Key</h2>
    <div class="inner">
      <%= form_for :akismet, :url => akismet_path, :html => { :class => :form } do |f| -%>
        <%= render :partial => "form", :locals => {:f => f} %>
      <% end -%>
    </div>
  </div>
</div>

app/views/akismets/show.html.erb
<% if @current_user.pixnet.present? %>
  <ul data-role="listview">
    <li data-role="list-divider">Akismet 狀態</li>
    <li>
    <h3><%= Akismet.human_attribute_name(:apikey) %></h3>
    <p><strong><%= @akismet.apikey %></strong></p>
    <p>The key is <%= @akismet.validate ? "valid" : "not valid" %></p>
    </li>
    <li>
    <h3><%= Akismet.human_attribute_name(:enabled) %></h3>
    <p><strong><%= @akismet.enabled %></strong></p>
    </li>
    <li>
    <h3>已有 <%= @current_user.comments.confirmed.size %> 則迴響被處理</h3>
    <p><strong>目前有 <%= @current_user.comments.is_spam.size %> 則迴響被標示為廣告留言</strong></p>
    </li>
  </ul>
<p></p>
  <div data-role="controlgroup" data-type="horizontal">
    <%= link_to "#{t("web-app-theme.edit", :default => "Edit")}", edit_akismet_path, "data-role" => :button %>
    <%= link_to "#{t("web-app-theme.delete", :default => "Delete")}", akismet_path, :method => :delete, :confirm => "#{t("web-app-theme.confirm", :default => "Are you sure?")}", "data-role" => :button %>
  </div>
<% else %>
  若要使用 Akismet 功能，您必須先認證 <%= link_to "#{t("pplugin.pixnet_oauth", :default => "PIXNET OAuth")}", oauth_consumer_path("pixnet"), :rel => "external" %>
<% end %>